# Generated by Django 5.2.1 on 2025-07-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
